/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author cristobal
 */
public class IUPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IUPrincipal.class.getName());

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jautos = new javax.swing.JMenu();
        jautomoviles = new javax.swing.JMenu();
        jMarca = new javax.swing.JMenu();
        jventas = new javax.swing.JMenu();
        jvendedores = new javax.swing.JMenu();
        jCliente = new javax.swing.JMenu();
        jConsulta = new javax.swing.JMenu();
        jMaventa = new javax.swing.JMenu();
        jMbuscaventas = new javax.swing.JMenu();
        Venvendedores = new javax.swing.JMenu();
        jcredicesionario = new javax.swing.JMenu();
        jMSalir = new javax.swing.JMenu();
        jSalir = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jautos.setText("Automoviles");

        jautomoviles.setText("Automoviles");
        jautos.add(jautomoviles);

        jMarca.setText("Marca");
        jautos.add(jMarca);

        jMenuBar1.add(jautos);

        jventas.setText("Ventas");

        jvendedores.setText("Vendedores");
        jventas.add(jvendedores);

        jCliente.setText("Cliente");
        jventas.add(jCliente);

        jMenuBar1.add(jventas);

        jConsulta.setText("Consultar");

        jMaventa.setText("Mayor venta");
        jConsulta.add(jMaventa);

        jMbuscaventas.setText("Buscar vendedores");
        jConsulta.add(jMbuscaventas);

        Venvendedores.setText("Ventas vendedores");
        jConsulta.add(Venvendedores);

        jcredicesionario.setText("Creditos concesionario");
        jConsulta.add(jcredicesionario);

        jMenuBar1.add(jConsulta);

        jMSalir.setText("Salir");

        jSalir.setText("Salir");
        jMSalir.add(jSalir);

        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Venvendedores;
    public javax.swing.JMenu jCliente;
    public javax.swing.JMenu jConsulta;
    public javax.swing.JMenu jMSalir;
    private javax.swing.JMenu jMarca;
    public javax.swing.JMenu jMaventa;
    public javax.swing.JMenu jMbuscaventas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    public javax.swing.JMenu jSalir;
    public javax.swing.JMenu jautomoviles;
    public javax.swing.JMenu jautos;
    public javax.swing.JMenu jcredicesionario;
    public javax.swing.JMenu jvendedores;
    public javax.swing.JMenu jventas;
    // End of variables declaration//GEN-END:variables
}
