/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author cristobal
 */
public class IUPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IUPrincipal.class.getName());

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        j_datos = new javax.swing.JMenu();
        jautomoviles = new javax.swing.JMenuItem();
        jmarca = new javax.swing.JMenuItem();
        jventas = new javax.swing.JMenu();
        jVENDEDORES = new javax.swing.JMenuItem();
        Jcliente = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMayorventa = new javax.swing.JMenuItem();
        jbuscarven = new javax.swing.JMenuItem();
        ventasvende = new javax.swing.JMenuItem();
        jconcesionario = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        jMSALIR = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenu7.setText("jMenu7");

        jMenu8.setText("jMenu8");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenu11.setText("jMenu11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_datos.setText("Datos");

        jautomoviles.setText("Automoviles");
        j_datos.add(jautomoviles);

        jmarca.setText("Marca");
        j_datos.add(jmarca);

        jMenuBar1.add(j_datos);

        jventas.setText("Ventas");

        jVENDEDORES.setText("Vendedores");
        jVENDEDORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVENDEDORESActionPerformed(evt);
            }
        });
        jventas.add(jVENDEDORES);

        Jcliente.setText("Cliente");
        jventas.add(Jcliente);

        jMenuBar1.add(jventas);

        jMenu9.setText("Consultas");

        jMayorventa.setText("Mayor venta");
        jMenu9.add(jMayorventa);

        jbuscarven.setText("Buscar vendedores");
        jMenu9.add(jbuscarven);

        ventasvende.setText("Ventas vendedores");
        jMenu9.add(ventasvende);

        jconcesionario.setText("Credito concesionario");
        jMenu9.add(jconcesionario);

        jMenuBar1.add(jMenu9);

        jSalir.setText("Salir");

        jMSALIR.setText("Salir");
        jSalir.add(jMSALIR);

        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jVENDEDORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVENDEDORESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVENDEDORESActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Jcliente;
    public javax.swing.JMenuItem jMSALIR;
    public javax.swing.JMenuItem jMayorventa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    public javax.swing.JMenu jSalir;
    public javax.swing.JMenuItem jVENDEDORES;
    public javax.swing.JMenu j_datos;
    public javax.swing.JMenuItem jautomoviles;
    public javax.swing.JMenuItem jbuscarven;
    public javax.swing.JMenuItem jconcesionario;
    public javax.swing.JMenuItem jmarca;
    public javax.swing.JMenu jventas;
    public javax.swing.JMenuItem ventasvende;
    // End of variables declaration//GEN-END:variables
}
